// Generated by gencpp from file ros_mscl/SetFilterEuler.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETFILTEREULER_H
#define ROS_MSCL_MESSAGE_SETFILTEREULER_H

#include <ros/service_traits.h>


#include <ros_mscl/SetFilterEulerRequest.h>
#include <ros_mscl/SetFilterEulerResponse.h>


namespace ros_mscl
{

struct SetFilterEuler
{

typedef SetFilterEulerRequest Request;
typedef SetFilterEulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterEuler
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetFilterEuler > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::ros_mscl::SetFilterEuler&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetFilterEuler > {
  static const char* value()
  {
    return "ros_mscl/SetFilterEuler";
  }

  static const char* value(const ::ros_mscl::SetFilterEuler&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetFilterEulerRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetFilterEuler >
template<>
struct MD5Sum< ::ros_mscl::SetFilterEulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetFilterEulerRequest> should match
// service_traits::DataType< ::ros_mscl::SetFilterEuler >
template<>
struct DataType< ::ros_mscl::SetFilterEulerRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetFilterEulerResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetFilterEuler >
template<>
struct MD5Sum< ::ros_mscl::SetFilterEulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterEulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetFilterEulerResponse> should match
// service_traits::DataType< ::ros_mscl::SetFilterEuler >
template<>
struct DataType< ::ros_mscl::SetFilterEulerResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterEulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETFILTEREULER_H
