// Generated by gencpp from file ros_mscl/SetFilterHeading.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETFILTERHEADING_H
#define ROS_MSCL_MESSAGE_SETFILTERHEADING_H

#include <ros/service_traits.h>


#include <ros_mscl/SetFilterHeadingRequest.h>
#include <ros_mscl/SetFilterHeadingResponse.h>


namespace ros_mscl
{

struct SetFilterHeading
{

typedef SetFilterHeadingRequest Request;
typedef SetFilterHeadingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterHeading
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetFilterHeading > {
  static const char* value()
  {
    return "194939c001a63802dc4131cae92cda22";
  }

  static const char* value(const ::ros_mscl::SetFilterHeading&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetFilterHeading > {
  static const char* value()
  {
    return "ros_mscl/SetFilterHeading";
  }

  static const char* value(const ::ros_mscl::SetFilterHeading&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetFilterHeadingRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetFilterHeading >
template<>
struct MD5Sum< ::ros_mscl::SetFilterHeadingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetFilterHeadingRequest> should match
// service_traits::DataType< ::ros_mscl::SetFilterHeading >
template<>
struct DataType< ::ros_mscl::SetFilterHeadingRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetFilterHeadingResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetFilterHeading >
template<>
struct MD5Sum< ::ros_mscl::SetFilterHeadingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterHeadingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetFilterHeadingResponse> should match
// service_traits::DataType< ::ros_mscl::SetFilterHeading >
template<>
struct DataType< ::ros_mscl::SetFilterHeadingResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::SetFilterHeadingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETFILTERHEADING_H
