// Generated by gencpp from file ros_mscl/SetSensorVehicleFrameOffset.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H
#define ROS_MSCL_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H

#include <ros/service_traits.h>


#include <ros_mscl/SetSensorVehicleFrameOffsetRequest.h>
#include <ros_mscl/SetSensorVehicleFrameOffsetResponse.h>


namespace ros_mscl
{

struct SetSensorVehicleFrameOffset
{

typedef SetSensorVehicleFrameOffsetRequest Request;
typedef SetSensorVehicleFrameOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensorVehicleFrameOffset
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffset > {
  static const char* value()
  {
    return "17d27ff1259ce523baf9de57b7c37e18";
  }

  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffset&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetSensorVehicleFrameOffset > {
  static const char* value()
  {
    return "ros_mscl/SetSensorVehicleFrameOffset";
  }

  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffset&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffsetRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffset >
template<>
struct MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensorVehicleFrameOffsetRequest> should match
// service_traits::DataType< ::ros_mscl::SetSensorVehicleFrameOffset >
template<>
struct DataType< ::ros_mscl::SetSensorVehicleFrameOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffsetResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffset >
template<>
struct MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensorVehicleFrameOffsetResponse> should match
// service_traits::DataType< ::ros_mscl::SetSensorVehicleFrameOffset >
template<>
struct DataType< ::ros_mscl::SetSensorVehicleFrameOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensorVehicleFrameOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H
